### ISSUE TITLE
Cannot activate module on WHMCS 8.7

### ISSUE THREAD

**Issue by tdtmusic2** [namecheap/ssl-whmcs#85]
Hello. We are having an issue with the activation of the module in WHMCS. One we click on the activate button, we get the error bellow:

```
Oops!
Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, string given in /home/xxxx/public_html/billing/modules/servers/namecheapssl/namecheapapi.php:375
Stack trace:
#0 /home/xxxxx/public_html/billing/modules/servers/namecheapssl/namecheapapi.php(375): mysqli_num_rows('SELECT id FROM ...')
#1 /home/xxxxxx/public_html/billing/modules/addons/namecheap_ssl/namecheap_ssl.php(45): NcSql::numRows('SELECT id FROM ...')
#2 /home/xxxxxx/public_html/billing/admin/configaddonmods.php(0): namecheap_ssl_activate()
#3 {main}
```

**Comment by jas8522** [comment]
Try my fork of the module here: https://github.com/websavers/WHMCS-Namecheap-SSL

I just submit [a commit that should fix this](https://github.com/websavers/WHMCS-Namecheap-SSL/commit/09fe414e2f60289b78a17ca566651f4b8f0094f3). Let me know the results.
